"""Add login tokens

Revision ID: 59a7b609384e
Revises: 70049d08ca73
Create Date: 2021-12-10 15:53:06.970311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '59a7b609384e'
down_revision = '70049d08ca73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_tokens',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('google_subject', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_tokens')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_subject')
    # ### end Alembic commands ###
